from __future__ import annotations

from typing import Literal


RunEventType = Literal[
    "run_queued",
    "run_started",
    "run_completed",
    "run_partially_failed",
    "run_failed",
    "run_cancelled",
    "cancel_requested",
    "worker_started",
    "pipeline_started",
    "document_processing_started",
    "document_processing_finished",
    "connector_started",
    "connector_finished",
    "sources_discovered",
    "sources_finished",
    "source_queued",
    "source_started",
    "source_ignored",
    "source_skipped",
    "source_processing",
    "source_finished",
    "source_failed",
    "segments_created",
    "source_units_created",
    "segment_started",
    "segment_finished",
    "ingest_step_started",
    "ingest_step_finished",
    "ingest_step_skipped",
    "index_metadata_extract_started",
    "index_metadata_extract_finished",
    "auto_indexes_written",
    "pages_write_started",
    "pages_written",
    "source_record_write_started",
    "source_record_written",
    "scoped_lint_started",
    "scoped_lint_finished",
    "lint_step_started",
    "lint_step_finished",
    "lint_step_skipped",
    "report_write_started",
    "report_written",
    "scan_started",
    "scan_finished",
    "query_started",
    "query_index_loaded",
    "query_graph_scope_loaded",
    "query_finished",
    "model_call_started",
    "model_call_finished",
    "model_call_failed",
    "model_call_retrying",
    "model_output_invalid",
    "provider_admission_waiting",
]


KNOWN_RUN_EVENT_TYPES: set[str] = set(RunEventType.__args__)
