export const queryKeys = {
  health: ["health"] as const,
  config: ["config"] as const,
  configFormRoot: ["config-form"] as const,
  configForm: (configPath?: string | null) => ["config-form", configPath || "default"] as const,
  configDiagnosticsRoot: ["config-diagnostics"] as const,
  configDiagnostics: (configPath?: string | null) => ["config-diagnostics", configPath || "default"] as const,
  modelProvidersRoot: ["models", "providers"] as const,
  modelProviders: (configPath?: string | null) => ["models", "providers", configPath || "default"] as const,
  sourceCatalogRoot: ["sources", "catalog"] as const,
  vaults: (configPath?: string | null) => ["vaults", configPath || "default"] as const,
  doctor: (configPath?: string | null) => ["doctor", configPath || "default", "light"] as const,
  sourceCatalog: (configPath?: string | null) => ["sources", "catalog", configPath || "default"] as const,
  sourceChatSessions: (vaultId: string) => ["sources", "knoarbor-chat-sessions", vaultId] as const,
  status: (vaultId: string) => ["vault", vaultId, "status"] as const,
  reports: (vaultId: string) => ["vault", vaultId, "reports"] as const,
  activeRuns: (vaultId: string) => ["vault", vaultId, "runs", "active"] as const,
  recentRuns: (vaultId: string) => ["vault", vaultId, "runs", "recent"] as const,
  runChatSessions: (vaultId: string) => ["vault", vaultId, "runs", "chat-sessions"] as const,
  sidebarChatSessionsRoot: ["sidebar-chat-sessions"] as const,
  sidebarChatSessions: (configPath?: string | null, vaultKey = "default") => ["sidebar-chat-sessions", configPath || "default", vaultKey || "default"] as const,
  overview: (vaultId: string) => ["vault", vaultId, "overview"] as const,
  graph: (vaultId: string, view = "page") => ["vault", vaultId, "graph", view] as const,
  pages: (vaultId: string) => ["vault", vaultId, "pages"] as const,
  queryTrends: (vaultId: string) => ["vault", vaultId, "query-trends"] as const,
};
