import type { ConfigFormProvider, ConfigImageProvider } from "../../api/client";

export const PROVIDER_PRESETS: ConfigFormProvider[] = [
  {
    name: "deepseek",
    adapter: "openai_compatible",
    base_url: "https://api.deepseek.com",
    api_key_env: "DEEPSEEK_API_KEY",
    model: "deepseek-v4-flash",
    json_mode: true,
    verify_tls: true,
    tls_ca_file: "",
    context_window: null,
    max_output_tokens: null,
    api_key_configured: false,
  },
  {
    name: "openai",
    adapter: "openai_compatible",
    base_url: "https://api.openai.com/v1",
    api_key_env: "OPENAI_API_KEY",
    model: "gpt-4.1",
    json_mode: true,
    verify_tls: true,
    tls_ca_file: "",
    context_window: null,
    max_output_tokens: null,
    api_key_configured: false,
  },
  {
    name: "vllm",
    adapter: "openai_compatible",
    base_url: "http://localhost:8001/v1",
    api_key_env: "",
    model: "local-model",
    json_mode: true,
    verify_tls: true,
    tls_ca_file: "",
    context_window: 32768,
    max_output_tokens: 8000,
    api_key_configured: true,
  },
  {
    name: "ollama",
    adapter: "ollama",
    base_url: "http://localhost:11434",
    api_key_env: "",
    model: "qwen3.6:27b-q4_K_M",
    json_mode: true,
    verify_tls: true,
    tls_ca_file: "",
    context_window: 262144,
    max_output_tokens: 8000,
    extra_body: { think: false },
    api_key_configured: true,
  },
];

export const IMAGE_PROVIDER_PRESETS: ConfigImageProvider[] = [
  {
    name: "sensenova",
    adapter: "sensenova_image",
    base_url: "https://token.sensenova.cn/v1",
    endpoint_path: "/images/generations",
    api_key_env: "SENSENOVA_API_KEY",
    model: "sensenova-u1-fast",
    verify_tls: true,
    tls_ca_file: "",
    resolution: "2720*1536",
    num_inference_steps: 20,
    guidance: 4,
    extra_body: {},
    api_key_configured: false,
  },
];
