export const queryKeys = {
  health: ["health"] as const,
  config: ["config"] as const,
  modelProviders: (configPath?: string | null) => ["models", "providers", configPath || "default"] as const,
  vaults: (configPath?: string | null) => ["vaults", configPath || "default"] as const,
  doctor: (configPath?: string | null) => ["doctor", configPath || "default", "light"] as const,
  sourceCatalog: (configPath?: string | null) => ["sources", "catalog", configPath || "default"] as const,
  status: (vaultId: string) => ["vault", vaultId, "status"] as const,
  reports: (vaultId: string) => ["vault", vaultId, "reports"] as const,
  activeRuns: (vaultId: string) => ["vault", vaultId, "runs", "active"] as const,
  recentRuns: (vaultId: string) => ["vault", vaultId, "runs", "recent"] as const,
  overview: (vaultId: string) => ["vault", vaultId, "overview"] as const,
  graph: (vaultId: string) => ["vault", vaultId, "graph"] as const,
  pages: (vaultId: string) => ["vault", vaultId, "pages"] as const,
  queryTrends: (vaultId: string) => ["vault", vaultId, "query-trends"] as const,
};
